version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      #Checkout the code to working directory
      - checkout
      #Log the current branch
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}