version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      #Checkout the code to working directory
      - checkout
      #Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Install meteor
      - run:
          name: install meteor
          command: |
            meteor || curl https://install.meteor.com | /bin/sh
      - run:
          name: install npm packages
          command: |
             meteor npm install
      - run:
          name: unit tests
          command: npm test