version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      #Checkout the code to working directory
      - checkout
      # Restore local dependencies from cache
      - restore_cache:
           keys:
             - v1-dependencies-{{ checksum "package.json" }}
             - v1-dependencies-#install npm
             - build-meteor-system-{{ checksum "./.circleci/config.yml" }}
      # Install meteor
      - run:
          name: Install meteor
          command: |
            meteor || curl https://install.meteor.com | /bin/sh
      # https://github.com/meteor/meteor/issues/4019  - avoid mongodb error
      - run:
          name: Set up mongodb locale
          command: |
            sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y locales
            sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
            sudo dpkg-reconfigure --frontend=noninteractive locales
            sudo update-locale LANG=en_US.UTF-8
            export LANG=en_US.UTF-8
      - run:
          name: install npm packages
          command: |
             meteor npm install
             meteor npm install --save bcrypt
             npm install spacejam
      # Cache local dependencies if they don't exist
      - save_cache:
           name: Saving Cache - meteor build
           key: build-meteor-system-{{ checksum "./.circleci/config.yml" }}
           paths:
             - ~/.meteor
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      #tests
      - run:
          name: Unit tests
          command: npm test
      - store_test_results:
          path: ~/project/test-results.xml

  build_mobile_android:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-25-node8-alpha
    environment:
       ANDROID_HOME: /usr/local/android-sdk-linux
       JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      #Where are we
      - run:
          name: Show current branch, directory
          command: |
              echo ${CIRCLE_BRANCH}
              echo ${CIRCLE_WORKING_DIRECTORY}
      # Install meteor
      - run:
          name: Install meteor
          command: |
            meteor || curl https://install.meteor.com | /bin/sh
      - run:
          name: install npm packages
          command: |
             meteor npm install
      #Android platform
      - run:
          name: Android SDK Platform 25
          command: |
              if [ ! -d "/opt/android/android-sdk-linux/platforms/android-25" ]; then
                  echo y | android update sdk --no-ui --all --filter "android-25";
              fi
      - run:
          name: Android Support Repository, revision 39 / Local Maven repository for Support Libraries
          command: |
              if [ ! -d "/usr/local/android-sdk-linux/extras/android/m2repository/com/android/support/design/25.0.0" ]; then
                  echo y | android update sdk --no-ui --all --filter "extra-android-m2repository";
              fi
      - run:
          name: Meteor mobile build
          command: meteor build $HOME/build/Visitry/mobile --server https://dev.visitry.org
      - store_artifacts:
          path: ~/android
          destination: debug.apk
      - store_artifacts:
          path: ~/android
          destination: release-unsigned.apk
      - store_artifacts:
          path: ~/mobile/android/
          destination: Visitry.apk

  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      #Checkout the code to working directory
      - checkout
      # Install meteor
      - run:
          name: Install meteor
          command: |
            meteor || curl https://install.meteor.com | /bin/sh
            meteor npm install
            meteor npm install --save babel-runtime
      # https://github.com/meteor/meteor/issues/4019  - avoid mongodb error
      - run:
          name: Set up mongodb locale
          command: |
            sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y locales
            sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
            sudo dpkg-reconfigure --frontend=noninteractive locales
            sudo update-locale LANG=en_US.UTF-8
            export LANG=en_US.UTF-8
      # Install mup
      - run:
          name: Install mup
          command: sudo npm -g install mup
      - run:
          name: npm
          command: sudo npm -g install ssh2
      # Install AWS cli
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli
      - add_ssh_keys:
          fingerprints:
            - "09:a9:cf:5e:16:24:28:96:18:77:11:f1:a9:24:24:77"
       # Build project with different configuration based on
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
                aws s3 cp s3://visitry-build-info/site-ssl-certs/dev/bundle.crt .deploy/dev/bundle.crt
                aws s3 cp s3://visitry-build-info/site-ssl-certs/dev/private.key .deploy/dev/private.key
                ssh-add -l
                ls -a ../.ssh
                cd .deploy/dev && mup deploy
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo "Not yet configured"
            else
                echo "Not yet"
            fi
workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy_dev:
        jobs:
            #- build
            #- build_mobile_android
            # The deploy job will only run on the filtered branches and
            # require the build job to be successful before it starts
            - deploy:
            #    requires:
            #      - build
                filters:
                    branches:
                        only:
                            - dev
